ALTER TABLE session_attendance
ADD COLUMN attended_at DATETIME NULL,
ADD COLUMN check_in_time DATETIME NULL,
ADD COLUMN check_out_time DATETIME NULL,
ADD COLUMN status VARCHAR(20) NULL DEFAULT 'REGISTERED';
